CREATE DATABASE Biblioteca;

USE Biblioteca;

CREATE TABLE Pais(
	Id INT IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	Sigla CHAR(3) NOT NULL

	CONSTRAINT PK_IdPais PRIMARY KEY (Id)
);

CREATE TABLE Autor(
	Id INT IDENTITY,
	IdPaisDeOrigem INT NOT NULL, 
	Nome VARCHAR(255) NOT NULL,
	DataNascimento DATE NOT NULL

	CONSTRAINT PK_IdAutor PRIMARY KEY (Id),
	CONSTRAINT FK_IdPaisDeOrigem_Autor FOREIGN KEY (IdPaisDeOrigem) REFERENCES Pais (Id)
);

CREATE TABLE Livro(
	Id INT IDENTITY,
	IdAutor INT NOT NULL,
	Titulo VARCHAR(255) NOT NULL,
	Paginas INT NOT NULL,
	ISBN INT UNIQUE NOT NULL,
	QuantidadeEstoque INT NOT NULL

	CONSTRAINT PK_IdLivro PRIMARY KEY (Id)
);

ALTER TABLE Livro
ADD CONSTRAINT FK_IdAutor_Livro FOREIGN KEY (IdAutor) REFERENCES Autor (Id);

EXEC sp_help Livro;
