CREATE DATABASE LojaDeRoupas;

CREATE TABLE Pais(
	Id INT IDENTITY,
	Nome NVARCHAR(255) NOT NULL,
	Sigla CHAR(3) NOT NULL

	CONSTRAINT PK_IdPais PRIMARY KEY(Id)
);

CREATE TABLE UF(
	Id INT IDENTITY,
	Nome NVARCHAR(255) NOT NULL,
	Sigla CHAR(2) NOT NULL

	CONSTRAINT PK_IdUF PRIMARY KEY(Id)
);

CREATE TABLE Endereco(
	Id INT IDENTITY,
	IdPais INT NOT NULL,
	IdUF INT NOT NULL,
	CEP CHAR(8) NOT NULL,
	Logadouro NVARCHAR(255) NOT NULL,
	Numero VARCHAR(5) NOT NULL,
	Complemento NVARCHAR(1000) NULL,
	Bairro NVARCHAR(255) NOT NULL,
	Cidade NVARCHAR(255) NOT NULL

	CONSTRAINT PK_IdEndereco PRIMARY KEY (Id),
	CONSTRAINT FK_IdPais_Endereco FOREIGN KEY (IdPais) REFERENCES Pais (Id),
	CONSTRAINT FK_IdUF_Endereco FOREIGN KEY (IdUF) REFERENCES UF (Id)
); 

CREATE TABLE Contato(
	Id INT IDENTITY,
	ContatoPrincipal VARCHAR (11) NOT NULL, 
	TelefoneSecundario VARCHAR (11) NOT NULL

	CONSTRAINT PK_IdContato PRIMARY KEY (Id)
);

CREATE TABLE Cliente(
	Id INT IDENTITY,
	IdEndereco INT NOT NULL,
	IdContato INT NOT NULL,
	CPF CHAR(11) UNIQUE NOT NULL,
	Nome NVARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	DataNascimento DATE NOT NULL

	CONSTRAINT PK_IdCliente PRIMARY KEY (Id),
	CONSTRAINT FK_IdEndereco_Cliente FOREIGN KEY (IdEndereco) REFERENCES Endereco (Id),
	CONSTRAINT FK_IdContato_Cliente FOREIGN KEY (IdContato) REFERENCES Contato (Id)
);

CREATE TABLE FormaDePagamento(
	Id INT IDENTITY,
	Nome NVARCHAR(255) NOT NULL

	CONSTRAINT PK_IdFormaDePagamento PRIMARY KEY (Id)
);

CREATE TABLE Venda(
	Id INT IDENTITY,
	IdCliente INT NOT NULL,
	IdFormaDePagamento INT NOT NULL,
	Data DATE NOT NULL

	CONSTRAINT PK_IdVenda PRIMARY KEY (Id),
	CONSTRAINT FK_IdCliente_Venda FOREIGN KEY (IdCliente) REFERENCES Cliente (Id),
	CONSTRAINT FK_IdFormaDePagamento_Venda FOREIGN KEY (IdFormaDePagamento) REFERENCES FormaDePagamento (Id)
);

CREATE TABLE Estilo(
	Id INT IDENTITY,
	Nome NVARCHAR(255) NOT NULL

	CONSTRAINT PK_IdEstilo PRIMARY KEY (Id)
);

CREATE TABLE Fornecedor(
	Id INT IDENTITY,
	IdContato INT NOT NULL,
	IdEndereco INT NOT NULL,
	Nome NVARCHAR(255) NOT NULL,
	CNPJ CHAR(14) UNIQUE NOT NULL,
	Email VARCHAR(255) NOT NULL

	CONSTRAINT PK_IdFornecedor PRIMARY KEY (Id),
	CONSTRAINT FK_IdContato_Fornecedor FOREIGN KEY (IdContato) REFERENCES Contato (Id),
	CONSTRAINT FK_IdEndereco_Fornecedor FOREIGN KEY (IdEndereco) REFERENCES Endereco (Id)
);

CREATE TABLE Produto(
	Id INT IDENTITY,
	IdEstilo INT NOT NULL,
	IdFornecedor INT NOT NULL,
	Nome NVARCHAR(255) NOT NULL,
	QuantidadeEstoque INT NOT NULL,
	PrecoUnitario DECIMAL(10,2) NOT NULL,
	Tamanho CHAR(3) NOT NULL

	CONSTRAINT PK_IdProduto PRIMARY KEY (Id),
	CONSTRAINT FK_IdEstilo_Produto FOREIGN KEY (IdEstilo) REFERENCES Estilo (Id),
	CONSTRAINT FK_IdFornecedor_Produto FOREIGN KEY (IdFornecedor) REFERENCES Fornecedor (Id)
);

CREATE TABLE VendaProduto(
	Id INT IDENTITY,
	IdVenda INT NOT NULL,
	IdProduto INT NOT NULL,
	Quantidade INT NOT NULL,
	Valor DECIMAL(10,2) NOT NULL

	CONSTRAINT PK_IdVendaProduto PRIMARY KEY (Id),
	CONSTRAINT FK_IdVenda_VendaProduto FOREIGN KEY (IdVenda) REFERENCES Venda (Id),
	CONSTRAINT FK_IdProduto_VendaProduto FOREIGN KEY (IdProduto) REFERENCES Produto (Id)
); 
