CREATE DATABASE Biblioteca2;

USE Biblioteca2;

CREATE TABLE Pais(
	Id INT IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	SIGLE VARCHAR(3) NOT NULL

	CONSTRAINT PK_IdPais PRIMARY KEY (Id)
);

CREATE TABLE Autor(
	Id INT IDENTITY,
	IdPais INT NOT NULL,
	Nome VARCHAR(255) NOT NULL,

	CONSTRAINT PK_IdAutor PRIMARY KEY (Id)
);

ALTER TABLE Autor
ADD CONSTRAINT FK_IdPais_Autor 
FOREIGN KEY (IdPais) 
REFERENCES Pais (Id);

CREATE TABLE Livro(
	Id INT IDENTITY,
	IdAutor INT NOT NULL,
	Titulo VARCHAR(255) NOT NULL,
	ISBN VARCHAR(14) NOT NULL,
	AnoPublicacao VARCHAR(4) NOT NULL,

	CONSTRAINT PK_IdLivro PRIMARY KEY (Id),
	CONSTRAINT UQ_ISBN_Autor UNIQUE (ISBN),
	CONSTRAINT FK_IdAutor_Livro FOREIGN KEY (IdAutor) REFERENCES Autor (Id)
);

CREATE TABLE Cliente(
	Id INT IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	CPF CHAR(11) NOT NULL,

	CONSTRAINT PK_IdCliente PRIMARY KEY (Id),
	CONSTRAINT UQ_CPF_Cliente UNIQUE (CPF)
);

CREATE TABLE Emprestimo(
	Id INT IDENTITY,
	IdCliente INT NOT NULL,
	IdLivro INT NOT NULL,
	DataEmprestimo DATE NOT NULL,
	DataPrevisaoDevolucao DATE NOT NULL,
	DateRealDevolucao DATE NOT NULL

	CONSTRAINT PK_IdEmprestimo PRIMARY KEY (Id),
	CONSTRAINT FK_IdCliente_Emprestimo FOREIGN KEY (IdCLiente) REFERENCES Cliente (Id),
	CONSTRAINT FK_IdLivro_Emprestimo FOREIGN KEY (IdLivro) REFERENCES Livro (Id)
);

ALTER TABLE Livro
ADD Preco DECIMAL(10,2) NOT NULL;

EXEC sp_help Livro;

EXEC sp_rename 'Emprestimo', 'Emprestimos';

EXEC sp_help Emprestimos;

ALTER TABLE Cliente
ADD Email VARCHAR(255) NOT NULL;

SELECT name
FROM sys.tables;

EXEC sp_help Pais;

EXEC sp_rename 'Pais.SIGLE', 'Sigla', 'COLUMN';

EXEC sp_help Autor;
