CREATE DATABASE Papelaria;

USE Papelaria;

CREATE TABLE Cliente (
	Id INT IDENTITY,
	NomeCompleto VARCHAR(150) NOT NULL,
	CPF CHAR(11) NOT NULL, 
	Telefone VARCHAR(15) NOT NULL

	CONSTRAINT Pk_IdCliente PRIMARY KEY (Id),
	CONSTRAINT UQ_CPF_Cliente UNIQUE (CPF)
);

CREATE TABLE Fornecedor (
	Id  INT IDENTITY,
	NomeFantasia VARCHAR(150) NOT NULL,
	Email VARCHAR(200) NOT NULL,
	Telefone VARCHAR(15) NOT NULL,
	CNPJ CHAR(14) NOT NULL

	CONSTRAINT Pk_IdFornecedor PRIMARY KEY (Id),
	CONSTRAINT UQ_CNPJ_Fornecesor UNIQUE (CNPJ)
);

CREATE TABLE Venda (
	Id INT IDENTITY,
	IdCliente INT NOT NULL,
	DataVenda DATE DEFAULT getdate() NOT NULL

	CONSTRAINT Pk_IdVenda PRIMARY KEY (Id),
	CONSTRAINT Fk_Cliente_Venda FOREIGN KEY (IdCliente) REFERENCES Cliente (Id)
);

CREATE TABLE Produto (
	Id INT IDENTITY,
	IdFornecedor INT NOT NULL,
	Nome VARCHAR(200) NOT NULL,
	Categoria VARCHAR(255) NOT NULL,
	PrecoUnitario DECIMAL (10,2) NOT NULL,
	Estoque INT NOT NULL

	CONSTRAINT Id_Produto PRIMARY KEY (Id),
	CONSTRAINT FK_IdFornecedor_Produto FOREIGN KEY (IdFornecedor) REFERENCES Fornecedor (Id)
);

CREATE TABLE VendaProduto (
	Id INT IDENTITY,
	IdVenda INT NOT NULL,
	IdProduto INT NOT NULL,
	Quantidade INT NOT NULL,
	PrecoUnitario DECIMAL NOT NULL,

	CONSTRAINT Pk_IdVendaProdutoFornecedor PRIMARY KEY (Id),
	CONSTRAINT Fk_IdVenda_VendaProduto FOREIGN KEY (IdVenda) REFERENCES Venda (Id),
	CONSTRAINT Fk_Produto_VendaProduto FOREIGN KEY (IdProduto) REFERENCES Produto (Id)
);
