CREATE DATABASE LojaDeRoupas;

CREATE TABLE Pais(
	Id INT IDENTITY,
	Nome NVARCHAR(255) NOT NULL,
	Sigla CHAR(3) NOT NULL

	CONSTRAINT PK_IdPais PRIMARY KEY(Id)
);

CREATE TABLE UF(
	Id INT IDENTITY,
	Nome NVARCHAR(255) NOT NULL,
	Sigla CHAR(2) NOT NULL

	CONSTRAINT PK_IdUF PRIMARY KEY(Id)
);

CREATE TABLE Endereco(
	Id INT IDENTITY,
	IdPais INT NOT NULL,
	IdUF INT NOT NULL,
	CEP CHAR(8) NOT NULL,
	Logadouro NVARCHAR(255) NOT NULL,
	Numero VARCHAR(5) NOT NULL,
	Complemento NVARCHAR(1000) NULL,
	Bairro NVARCHAR(255) NOT NULL,
	Cidade NVARCHAR(255) NOT NULL

	CONSTRAINT PK_IdEndereco PRIMARY KEY (Id),
	CONSTRAINT FK_IdPais_Endereco FOREIGN KEY (IdPais) REFERENCES Pais (Id),
	CONSTRAINT FK_IdUF_Endereco FOREIGN KEY (IdUF) REFERENCES UF (Id)
); 

CREATE TABLE Contato(
	Id INT IDENTITY,
	ContatoPrincipal VARCHAR (11) NOT NULL, 
	TelefoneSecundario VARCHAR (11) NOT NULL

	CONSTRAINT PK_IdContato PRIMARY KEY (Id)
);

CREATE TABLE Cliente(
	Id INT IDENTITY,
	IdEndereco INT NOT NULL,
	IdContato INT NOT NULL,
	CPF CHAR(11) UNIQUE NOT NULL,
	Nome NVARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	DataNascimento DATE NOT NULL

	CONSTRAINT PK_IdCliente PRIMARY KEY (Id),
	CONSTRAINT FK_IdEndereco_Cliente FOREIGN KEY (IdEndereco) REFERENCES Endereco (Id),
	CONSTRAINT FK_IdContato_Cliente FOREIGN KEY (IdContato) REFERENCES Contato (Id)
);
