CREATE DATABASE Escola2;

USE Escola2;

CREATE TABLE Curso(
	Id INT IDENTITY,
	Nome VARCHAR(255) NOT NULL,

	CONSTRAINT PK_IdCurso PRIMARY KEY (Id)
);

CREATE TABLE Aluno(
	Id INT IDENTITY,
	IdCurso INT NOT NULL,
	Nome VARCHAR(255) NOT NULL,
	Media DECIMAL(2,2) NOT NULL

	CONSTRAINT PK_IdAluno PRIMARY KEY (Id)
	CONSTRAINT FK_IdCurso_Aluno FOREIGN KEY (IdCurso) REFERENCES Curso (Id)
);

CREATE TABLE Livro(
	Id INT IDENTITY,
	Titulo VARCHAR(255) NOT NULL,
	PrecoUnitario DECIMAL(10,2) NOT NULL,

	CONSTRAINT PK_IdLivro PRIMARY KEY (Id)
);

CREATE TABLE Reserva(
	Id INT IDENTITY,
	IdLivro INT NOT NULL,
	IdAluno INT NOT NULL,
	DataReserva DATETIME DEFAULT GETDATE(),
	DataDevolucaoPrevista DATETIME DEFAULT DATEADD(DAY, 14, GETDATE())
	
	CONSTRAINT PK_IdReserva PRIMARY KEY (Id),
	CONSTRAINT FK_IdLivro_Reserva FOREIGN KEY (IdLivro) REFERENCES Livro (Id),
	CONSTRAINT FK_IdAluno_Reserva FOREIGN KEY (IdAluno) REFERENCES Aluno (Id)
);
